// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi9zLfpcmCOjpdS5WHdzYKRisiPWKN8vk',
    appId: '1:140185584841:web:f6d56c641bd6eec477b918',
    messagingSenderId: '140185584841',
    projectId: 'bgmi-d4a57',
    authDomain: 'bgmi-d4a57.firebaseapp.com',
    storageBucket: 'bgmi-d4a57.firebasestorage.app',
    measurementId: 'G-F01XRZVLWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA89CCCCDkoH0qT1tfy2xMJdXwmlP3pCS0',
    appId: '1:140185584841:android:7900962ca2687a3477b918',
    messagingSenderId: '140185584841',
    projectId: 'bgmi-d4a57',
    storageBucket: 'bgmi-d4a57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4qNPqKPRNM5EVAYgX3qQZEkHUQXSFQ94',
    appId: '1:140185584841:ios:f02e826ad125740d77b918',
    messagingSenderId: '140185584841',
    projectId: 'bgmi-d4a57',
    storageBucket: 'bgmi-d4a57.firebasestorage.app',
    iosBundleId: 'com.example.bgmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi9zLfpcmCOjpdS5WHdzYKRisiPWKN8vk',
    appId: '1:140185584841:web:758b0ae2d00a1b1677b918',
    messagingSenderId: '140185584841',
    projectId: 'bgmi-d4a57',
    authDomain: 'bgmi-d4a57.firebaseapp.com',
    storageBucket: 'bgmi-d4a57.firebasestorage.app',
    measurementId: 'G-41VBKMWSMT',
  );
}
